### ISSUE TITLE
Add stringify method?

### ISSUE THREAD

**Issue by eight04** [errwischt/stacktrace-parser#13]
I want to parse the stack, edit them, and format them back to a string to customize an error object. Is it possible to:

1. Make the parse result include the error message (description) and
2. Add a method to convert the parse result back to the string?

**Comment by Calamari** [comment]
Hi.

Well, I am not quite sure how you use it, but this library but somewhere you already catch the error. The parser only takes the stack of that error, so technically you could just remit it. Although I am not quite sure what exactly it is you want to achieve with it.

But something along the line of this should do the trick (slightly adapted from the README and untested):

```js
import * as stackTraceParser from 'stacktrace-parser';

try {
  throw new Error('My error');
} catch(ex) {
  const stack = stackTraceParser.parse(ex.stack);
  ex.stack = stack.map(line => `${line.method}@${line.file}:${line.lineNumber}:${line.column}`).join("\n")
  // ex is now
}

Does this help?
I am curious, why you want to do this. If you may want to share your use case :)
```

**Comment by eight04** [comment]
I want to test a large object against a large JSON file (expected result). Although the built-in `assert.deepStrictEqual` can generate a nice diff, it doesn't tell you where and it is hard to find it when there are hundreds of lines. I want to modify the stack/message to output the line number.

After some searching, it seems that I should use `Error.captureStackTrace` to generate a new stack instead of editing it.
