### ISSUE TITLE
Publishing 0.1.2 to npm

### ISSUE THREAD

**Issue by ide** [errwischt/stacktrace-parser#3]
Could you publish a new release to npm when you have a chance?

**Comment by Calamari** [comment]
Thought about doing something more, that's why I haven't done it right away. But it's done now.
Enjoy.

**Comment by ide** [comment]
Thanks so much. This will make installing React Native on io.js a little bit nicer!

**Comment by Calamari** [comment]
I wonder if React Native only works for iOS or if there is also an Android version :)

**Comment by ide** [comment]
I believe Android is coming before the end of this year (probably much sooner, but I don't want to speak for the team)!
